### ISSUE TITLE
ResNet-101 baseline 

### ISSUE THREAD

**Issue by MalharJ** [facebookresearch/ImageNet-Adversarial-Training#21] opened 2020-05-27 21:09 UTC
In the paper its mentioned that the baselines compared against are adversarially robust ResNet-101 and ResNet-152. Will the ResNet-101 baseline model be available?

**Comment by ppwwyyxx** [comment] 2020-05-27 21:15
duplicate of #6

**Closed as completed by ppwwyyxx** 2020-05-27 21:15 UTC
